
[functions.create-order]
enabled = true
verify_jwt = true
import_map = "./functions/create-order/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-order/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-order/*.html" ]

[functions.verify-payment]
enabled = true
verify_jwt = true
import_map = "./functions/verify-payment/deno.json"
entrypoint = "./functions/verify-payment/index.ts"

[functions.cancel-payment]
enabled = true
verify_jwt = true
import_map = "./functions/verify-payment/deno.json"
entrypoint = "./functions/cancel-payment/index.ts"

[functions.create-notification]
enabled = true
verify_jwt = true
import_map = "./functions/create-notification/deno.json"
entrypoint = "./functions/create-notification/index.ts"
